services:
  pocketbase:
    build:
      context: ./pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations:ro
      - ./pocketbase/pb_hooks:/pb/pb_hooks:ro

volumes:
  pocketbase_data:
