/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliciesNewRouteImport } from './routes/policies.new'
import { Route as PoliciesPolicyIdRouteImport } from './routes/policies.$policyId'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesNewRoute = PoliciesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PoliciesRoute,
} as any)
const PoliciesPolicyIdRoute = PoliciesPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => PoliciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/policies/new': typeof PoliciesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/policies/new': typeof PoliciesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/policies/new': typeof PoliciesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/policies' | '/policies/$policyId' | '/policies/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/policies' | '/policies/$policyId' | '/policies/new'
  id: '__root__' | '/' | '/policies' | '/policies/$policyId' | '/policies/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/new': {
      id: '/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof PoliciesNewRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/policies/$policyId': {
      id: '/policies/$policyId'
      path: '/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof PoliciesPolicyIdRouteImport
      parentRoute: typeof PoliciesRoute
    }
  }
}

interface PoliciesRouteChildren {
  PoliciesPolicyIdRoute: typeof PoliciesPolicyIdRoute
  PoliciesNewRoute: typeof PoliciesNewRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesPolicyIdRoute: PoliciesPolicyIdRoute,
  PoliciesNewRoute: PoliciesNewRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
